name: imvinhnguyen-com
region: sfo

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

domains:
  - domain: imvinhnguyen.com
    type: PRIMARY
    zone: imvinhnguyen.com
  - domain: www.imvinhnguyen.com
    type: ALIAS
    zone: imvinhnguyen.com

services:
  - name: sudovinh-imvinhnguyen
    github:
      repo: sudovinh/imvinhnguyen
      branch: main
      deploy_on_push: false
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30
